#!/bin/bash
#SBATCH --job-name=CELE_cat
#SBATCH --mem-per-cpu=5G
#SBATCH -n 6
#SBATCH -c 2
#SBATCH --output=CELE_cat_output.txt
#SBATCH --error=CELE_cat_error.txt

mkdir Samples_fastq
zcat ./Cutadapted/trimmed_GM1541-1*L00?_R1_001.fastq.gz > ./Samples_fastq/S1_PAO1_F1_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-2*L00?_R1_001.fastq.gz > ./Samples_fastq/S2_PAO1_F1_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-3*L00?_R1_001.fastq.gz > ./Samples_fastq/S3_PAO1_F1_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-4*L00?_R1_001.fastq.gz > ./Samples_fastq/S4_PAO1_F2_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-5*L00?_R1_001.fastq.gz > ./Samples_fastq/S5_PAO1_F2_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-6*L00?_R1_001.fastq.gz > ./Samples_fastq/S6_PAO1_F2_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-7*L00?_R1_001.fastq.gz > ./Samples_fastq/S7_OP50postPAO1_F3_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-8*L00?_R1_001.fastq.gz > ./Samples_fastq/S8_OP50postPAO1_F3_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-9*L00?_R1_001.fastq.gz > ./Samples_fastq/S9_OP50postPAO1_F3_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-10*L00?_R1_001.fastq.gz > ./Samples_fastq/S10_OP50postPAO1_F4_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-11*L00?_R1_001.fastq.gz > ./Samples_fastq/S11_OP50postPAO1_F4_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-12*L00?_R1_001.fastq.gz > ./Samples_fastq/S12_OP50postPAO1_F4_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-13*L00?_R1_001.fastq.gz > ./Samples_fastq/S13_PAO1_F5_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-14*L00?_R1_001.fastq.gz > ./Samples_fastq/S14_PAO1_F5_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-15*L00?_R1_001.fastq.gz > ./Samples_fastq/S15_PAO1_F5_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-16*L00?_R1_001.fastq.gz > ./Samples_fastq/S16_PAO1_F6_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-17*L00?_R1_001.fastq.gz > ./Samples_fastq/S17_PAO1_F6_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-18*L00?_R1_001.fastq.gz > ./Samples_fastq/S18_PAO1_F6_seq1.fastq

zcat ./Cutadapted/trimmed_GM1541-19*L00?_R1_001.fastq.gz > ./Samples_fastq/S19_OP50control_FX_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-20*L00?_R1_001.fastq.gz > ./Samples_fastq/S20_OP50control_FX_seq1.fastq
zcat ./Cutadapted/trimmed_GM1541-21*L00?_R1_001.fastq.gz > ./Samples_fastq/S21_OP50control_FX_seq1.fastq

zcat ./Cutadapted/trimmed_GM1541-10*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S10_OP50postPAO1_F4_seq3.fastq
zcat ./Cutadapted/trimmed_GM1541-11*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S11_OP50postPAO1_F4_seq3.fastq
zcat ./Cutadapted/trimmed_GM1541-12*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S12_OP50postPAO1_F4_seq3.fastq
zcat ./Cutadapted/trimmed_GM1541-14*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S14_PAO1_F5_seq3.fastq
zcat ./Cutadapted/trimmed_GM1541-15*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S15_PAO1_F5_seq3.fastq
zcat ./Cutadapted/trimmed_GM1541-17*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S17_PAO1_F6_seq3.fastq
zcat ./Cutadapted/trimmed_GM1541-18*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S18_PAO1_F6_seq3.fastq
zcat ./Cutadapted/trimmed_GM1541-21*L00?_R1_seq3.fastq.gz > ./Samples_fastq/S21_OP50control_FX_seq3.fastq
