#!/bin/bash
#SBATCH --job-name=CELE_bam_sort
#SBATCH --mem-per-cpu=5G
#SBATCH -n 6
#SBATCH -c 2
#SBATCH --output=CELE_sort_output.txt
#SBATCH --error=CELE_sort_error.txt

module load SAMtools

for bamfile in *.bam
do
samtools sort -o sorted_$bam.bam
done
