#!/bin/bash
#SBATCH --job-name=CELE_bam_sort
#SBATCH --mem-per-cpu=5G
#SBATCH -n 6
#SBATCH -c 2
#SBATCH --output=CELE_sort_output.txt
#SBATCH --error=CELE_sort_error.txt

module load SAMtools
mkdir Sorted

for file in ./Unsorted/*.bam
do
samtools sort -o ./Sorted/sorted_$file.bam $file

done


